Repository Shrey19702/LeetCode-Solutions-, pull requests merged in 2021-10, with the labels that each got.

#2 Create qno_509_fibbonaaccinumber.cpp
  LeetCode Qs/qno_509_fibbonaaccinumber.cpp
Labels: good first issue, hacktoberfest, good-first-contribution

#3 Add files via upload
  LeetCode Qs/kickstartarthmeticsqaure.cpp
  hackerrank/LEFTROTATION.cpp
  hackerrank/LEFTROTATION.exe
  hackerrank/alternatingcharacter.cpp
  hackerrank/alternatingcharacter.exe
  hackerrank/anagram.cpp
  hackerrank/anagram.exe
  hackerrank/arrayandsimplequeries.cpp
  hackerrank/arrayandsimplequeries.exe
  hackerrank/arraymanupulation(important).cpp
  hackerrank/countingvalley.cpp
  hackerrank/countingvalley.exe
  hackerrank/findingnearestrepeat.cpp
  hackerrank/findingnearestrepeat.exe
  hackerrank/findingpair.cpp
  hackerrank/findingpair.exe
  hackerrank/hourglass.cpp
  hackerrank/hourglass.exe
  hackerrank/insertimganode.cpp
  hackerrank/jumpingoncloud.cpp
  hackerrank/jumpingoncloud.exe
  hackerrank/minimumswap2.cpp
  hackerrank/minimumswap2.exe
  hackerrank/repeatedstring.cpp
  hackerrank/repeatedstring.exe
  hackerrank/rollercoster.cpp
  hackerrank/sherlockandvalidstring.cpp
  hackerrank/sherlockandvalidstring.exe
Labels: good first issue, question, hacktoberfest, good-first-contribution

#6 Create Intersection-of-Two-Linked-Lists.cpp
  LeetCode Qs/Intersection-of-Two-Linked-Lists.cpp
Labels: hacktoberfest, good-first-contribution, good-first-issue

#4 salary_question
  hackerrank/totalsalary.cpp
Labels: good first issue, hacktoberfest, good-first-contribution

#8 Create Kids-With-the-Greatest-Number-of-Candies.cpp
  LeetCode Qs/Kids-With-the-Greatest-Number-of-Candies.cpp
Labels: hacktoberfest, good-first-issue

#9 Create minmex2.cpp
  codeforces/minmex2.cpp
Labels: good first issue, hacktoberfest, good-first-contribution
